### ISSUE TITLE
Internal server error: <css input>:xxx:x: Unknown word

### ISSUE THREAD

**Issue by edanweis** [WJCHumble/vite-plugin-vue2-css-vars#1]
Just what I was looking for @WJCHumble, but I'm getting the above error for commented lines of code. I tried building this plugin with an updated vue-template-compiler @ `^2.6.14`. 

I also tried adding `postcss-scss` and `postcss.config.js` with 
```
// postcss.config.js
module.exports = {
  syntax: 'postcss-scss',
  plugins: {
    
  }
}
```

My dev dependencies are:
```
"devDependencies": {
    "@vue/compiler-sfc": "^3.0.11",
    "node-sass": "^5.0.0",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.2",
    "vite": "^2.2.3",
    "vite-plugin-vue-svg": "^0.1.0",
    "vuetify-loader": "^1.3.0"
  },
```

Any idea why?

**Comment by WJCHumble** [comment]
You should use the vue-template-compiler@2.6.12 version, because the `vite-plugin-vue2` need this version. @edanweis

**Comment by WJCHumble** [comment]
Vite is support postcss [https://vitejs.dev/config/#css-postcss](https://vitejs.dev/config/#css-postcss), you don't need create the postcss.config.js

**Comment by edanweis** [comment]
@WJCHumble I removed `@vue/compiler-sfc` and installed `vue-template-compiler@2.6.12` but I am still getting the same error. Is there anything else I should change in vite config?

**Comment by WJCHumble** [comment]
Can you provide a reproduction? @edanweis

**Comment by edanweis** [comment]
@WJCHumble  Thank you. https://github.com/edanweis/repro

**Comment by WJCHumble** [comment]
It is a bug, i will fix it. @edanweis

**Comment by WJCHumble** [comment]
@edanweis  It fixed in  `vite-plugin-vue2-css-vars@0.1.7`.

**Comment by edanweis** [comment]
@WJCHumble  I am still getting the same error after installing `vite-plugin-vue2-css-vars@0.1.7`. Are you able to submit a PR to [edanweis/repro](https://github.com/edanweis/repro) for me to check?

It works if I remove the `//` commented style.

**Comment by WJCHumble** [comment]
@edanweis Sorry my mistake, you can use `vite-plugin-vue2-css-vars@0.1.8` now.

**Comment by edanweis** [comment]
Sorry @WJCHumble Now I get:
```
failed to load config from C:\Users\EdanWeis\repro\vite.config.js
error when starting dev server:
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Users\EdanWeis\repro\node_modules\postcss-scss\lib\nested-declaration.js:3:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\EdanWeis\AppData\Roaming\nvm\v12.18.4\node_modules\vite\dist\node\chunks\dep-994e0558.js:46479:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\EdanWeis\repro\node_modules\postcss-scss\lib\scss-parser.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\EdanWeis\AppData\Roaming\nvm\v12.18.4\node_modules\vite\dist\node\chunks\dep-994e0558.js:46479:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by WJCHumble** [comment]
@edanweis Maybe you can try to run the following command, and then restart your project:
```
rm -r node_modules
npm cache clean -f
rm package-lock.json
npm i
```

**Comment by edanweis** [comment]
@WJCHumble I am using pnpm and another error has come up when no style tags are used -  #2
